### ISSUE TITLE
Add padding to stepped list detailed

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#1917]
## Pattern to amend
Stepped-list--detailed

## Context
The sections/descriptions part of the step has no padding between the one above. This makes it difficult to work out when one step stops and the next starts. This has been polyfilled on www.ubuntu.com with the following code:
```css
.p-stepped-list--detailed .p-list-step__item {
  margin-top: 1rem;
}
```
