### ISSUE TITLE
Checkbox has no focus state

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2199]
## Pattern to amend
Base checkbox

## Context
Base checkboxes do not have focus state. Needs something like:
```css
input[type="checkbox"]:focus + label::before {
  outline: 1px solid #19b6ee;
  outline-offset: 0;
}
```
