### ISSUE TITLE
No visible styling in Firefox for <b>, <dt>, or <strong>

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2272]
Vanilla contains
```css
b, strong {
    font-weight: bolder;
}
```

which is then partly overridden by
```css
dt, strong, .p-notification__status {
    font-weight: 400;
}
```

But neither of these has any effect in Firefox:

![vanilla-bold-missing](https://user-images.githubusercontent.com/19801137/55943069-bb800300-5c3d-11e9-9956-512c09efbdce.png)

This is because Firefox applies the bold weight only with `{font-weight: 600}` or higher:

![vanilla-bold-600](https://user-images.githubusercontent.com/19801137/55943260-27fb0200-5c3e-11e9-9770-8c2dc9b4b09d.png)

With `{font-weight: 599}` or lower, Firefox just uses the regular weight:

![vanilla-bold-599](https://user-images.githubusercontent.com/19801137/55943349-57aa0a00-5c3e-11e9-95b6-b25f3b9d7feb.png)

[Originally discovered [on docs.snapcraft.io](https://github.com/canonical-websites/docs.snapcraft.io/issues/133).]
