### ISSUE TITLE
Error importing individual components

### ISSUE THREAD

**Issue by k-ivan** [canonical-web-and-design/vanilla-framework#2391]
**Describe the bug**
I try to use only the components I need, but I get an error.
```
Error: ".p-stepped-list__title" failed to @extend "%numbered-step-title".
       The selector "%numbered-step-title" was not found.
```

**To Reproduce**
1. `npm install vanilla-framework`
2. My `app.scss` contains the code from the documentation
```scss
// Import Vanilla framework
@import 'vanilla-framework/scss/vanilla';

// Include base Vanilla styles
@include vf-base;

// Include the components you want
@include vf-p-buttons;
@include vf-p-forms;
@include vf-p-links;
```
3. launch gulp task for compilation scss
4. getting an error
```sh
Message:
    node_modules/vanilla-framework/scss/_patterns_lists.scss
Error: ".p-stepped-list__title" failed to @extend "%numbered-step-title".
       The selector "%numbered-step-title" was not found.
       Use "@extend %numbered-step-title !optional" if the extend should be able to fail.
        on line 182 of node_modules/vanilla-framework/scss/_patterns_lists.scss
>>   @extend %numbered-step-title;
```

**Expected behavior**
I would like to include to the project only the necessary components.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/6150895/59973548-1ae98000-95aa-11e9-818a-62afece2a861.png)

**Additional context**
If including all of Vanilla, everything works.

**Comment by anthonydillon** [comment]
Thank you for taking the time to report this issue. It looks like we are cross inheriting elements of some components. We will try and get this resolved in a soon release.

In the mean time, added the below placeholder between the include of base and the patterns:

```scss
%numbered-step-title {
    display: flex;

    &::before {
      align-self: start;
      background-color: $color-mid-x-light;
      border-radius: 100%;
      content: counter(li);
      counter-increment: li;
      direction: rtl;
      display: block;
      text-align: center;
    }
  }
```
