### ISSUE TITLE
Middot is not responsive to its background

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2395]
## Pattern to amend
p-inline-list--middot

## Visual
![Screenshot_2019-06-26 Vanilla documentation](https://user-images.githubusercontent.com/1413534/60164838-2df09000-97f6-11e9-87b4-fae09f3b74f5.png)

## Context
The middot stays grey on dark backgrounds. I think it should switch to white if in a `strip--dark` or `is-dark` strip. Also the dots are very small. I think they should be bumped in size as they are in the new JAAS design:
![Screenshot_2019-06-26 Jujucharms Juju](https://user-images.githubusercontent.com/1413534/60165009-7c9e2a00-97f6-11e9-9323-fbee34a0fd5b.png)

**Comment by anthonydillon** [comment]
This is how I solved it locally:
```scss
@mixin jaas-p-lists {
  @include jaas-p-inline-list-middot;
}

@mixin jaas-p-inline-list-middot {
  .p-inline-list--middot {
    @at-root .is-dark .p-inline-list__item::after {
      color: $color-x-light;
      font-size: 2em;
      right: -.4em;
      top: .3em;
    }
  }
}
```
