### ISSUE TITLE
Spacing below tables and divs

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/vanilla-framework#2420]
@barrymcgee [discovered a couple of spacing issues](https://github.com/canonical-web-and-design/maas.io/pull/346#pullrequestreview-265511957) in the MAAS docs work.

I [fixed](https://github.com/canonical-web-and-design/maas.io/pull/346/commits/f85a8014a4a34ba596b937ace80f08495b930ddf) both issues in the local project, but I think maybe we should consider whether Vanilla core should have taken care of them.

In the case of the tables, where an `<h2>` directly following a `<table>` has no space between the two, the issue was because the spacing that would normally appear above headings comes from this logic (as in, explicitly only apples when `h2`s follow `p` elements):

``` css
p:not([class*="p-heading--"]):not([class*="p-muted-heading"]) + h2,
p:not([class*="p-heading--"]):not([class*="p-muted-heading"]) + .p-heading--two {
    padding-top: 1.6rem;
}
```

This could be fixed by simply adding `table` into the selectors for the above rule, but it seems like we might be chasing our tail with that solution because there are almost certainly other basic elements that would cause the same problem. It would seem to me that we'd be better off with a catch-all rule of some sort, like `h2:not(:first-child) {padding-top: 1.6rem;}` which we then override for any special cases we need (e.g. `p[class*="p-heading--"][class*="p-muted-heading"] + h2 {padding-top: 0}`). Of course I don't know the history here.

If we did find a more generic version of the solution then it could solve the second problem I had, which was about a `p-notification` following a standard `div`.

For your consideration.
