### ISSUE TITLE
Justify buttons in rows

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#2463]
The buttons in a table row are helpfully narrower, but possibly they should also move up a bit to not make the row larger than normal text content. See this comment: https://app.zeplin.io/project/5ce5423a25863c1e0d7abb27/screen/5d36e2233615fbb2789ce87f (the relevant bit being: "Please note the icons will need to have some negative margin-top and bottom in order to not "swell" tds.they need to overlap the .25rem td padding.")

In MAAS I've resolved this with:

```css
td:not(.p-table-expanding__panel) [class*="p-button"] {
  margin-top: -0.25rem;
  margin-bottom: -0.25rem;
}
```
