### ISSUE TITLE
_vanilla.scss import throws an error

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanilla-framework#2487]
**Describe the bug**

`_vanilla.scss` import throws an error - see the following code:

```scss
// This import works
// @import "../node_modules/vanilla-framework/scss/settings_colors";

// This import throws an error 
@import "../node_modules/vanilla-framework/scss/vanilla";

body {
  background: $color-light;
}
```

Error:

```
CompileError
Error: "%vf-meta-list-item" failed to @extend "%small-text".
       The selector "%small-text" was not found.
       Use "@extend %small-text !optional" if the extend should be able to fail.
        on line 10:11 of node_modules/vanilla-framework/scss/_patterns_media-object.scss
```

This can be reproduced live here: https://codesandbox.io/s/wispy-shadow-3iv9r
