### ISSUE TITLE
Form validation text too close to input when $multi = 1

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#2513]
- Form validation text too close to input when $multi = 1.
- Vanilla 2.3.0.
- Only noticeable if the input does not have help text.

### Current:
![screenshot_9](https://user-images.githubusercontent.com/25733845/63682607-9bba3780-c7f8-11e9-98ea-5cdd64cf0682.png)

### Expected:
![screenshot_10](https://user-images.githubusercontent.com/25733845/63682581-8e04b200-c7f8-11e9-80b0-e81411a9d5fe.png)

I fixed this in `maas-ui` with:
``` scss
:not(.p-form-help-text) ~ .p-form-validation__message {
  margin-top: 0;
}
```
