### ISSUE TITLE
“Show” page: All examples always show regardless of width

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2600]
1\. Go to [the “Show” page](https://docs.vanillaframework.io/utilities/show/).
2\. Resize the browser window to any size you like.

What happens:
1\. The “Shown on small screens”, “Shown on medium screens”, and “Shown on large screens” lines are all visible simultaneously.
2\. All three examples continue to be shown regardless of window size.

Small window example:

![image](https://user-images.githubusercontent.com/19801137/67503262-3c08cd00-f67f-11e9-8624-04d76f9357b8.png)

Large window example:

![image](https://user-images.githubusercontent.com/19801137/67503493-a3bf1800-f67f-11e9-981b-b5411b3a0944.png)

What should happen: Elements with only one of the classes should be visible at a time.

**Comment by matthewpaulthomas** [comment]
As far as I can tell, the only code that acts on the `u-show--*` classes is this, in `build.css`:
```css
@media screen and (max-width: 772px) {
 .u-show--small {
  display:inherit !important
 }
}
@media (min-width: 772px) and (max-width: 1036px) {
 .u-show--medium {
  display:inherit !important
 }
}
@media screen and (min-width: 1036px) {
 .u-show--large {
  display:inherit !important
 }
}
```
And this, in `styles.css`, identical except for different breakpoints:
```css
@media screen and (max-width: 900px) {
 .u-show--small {
  display:inherit !important
 }
}
@media (min-width: 900px) and (max-width: 1036px) {
 .u-show--medium {
  display:inherit !important
 }
}
@media screen and (min-width: 1036px) {
 .u-show--large {
  display:inherit !important
 }
}
```

There doesn’t seem to be any code anywhere that _hides_ any of these classes, so code to reveal them has no effect.
