### ISSUE TITLE
.p-divider has no min-height

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/vanilla-framework#3086]
**Describe the bug**

For p-divider blocks with single lines of text, the blocks are too small to make the divider visible.

**To Reproduce**

1. Go to https://canonical.com/#partners
2. In the inspector, remove has-min-height from the row of links
3. See error that the divider lines do not have enough height to be seen

**Expected behavior**

Even with a single line of text, you should be able to see the divider line

**Screenshots**

original
![image](https://user-images.githubusercontent.com/441217/82580671-5a886580-9b87-11ea-8c54-f0512403be79.png)

fix
![image](https://user-images.githubusercontent.com/441217/82580653-52302a80-9b87-11ea-9e46-7e118a520522.png)

Here is the code used to fix the issue:

```scss
  .p-divider.has-min-height {
    @media screen and(min-width: $breakpoint-medium) {
      .p-divider__block:not(:nth-child(1))::before {
        min-height: 1.5rem;
        top: 0;
      }
    }
  }
```
