### ISSUE TITLE
Add is-wide to the inline-images pattern

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3294]
## Pattern to amend
[p-inline-images](https://vanillaframework.io/docs/patterns/inline-images).

## Visual
Before:
![image](https://user-images.githubusercontent.com/1413534/93887210-53609800-fcde-11ea-9ed9-282b66682f37.png)

After:
![image](https://user-images.githubusercontent.com/1413534/93887260-62474a80-fcde-11ea-85b8-163b6af0deb9.png)

## Context
The inline images pattern lays out similar aspect ratio images but if one is wider then height then it comes small. We often have copied around the `is-wide` class to extend the pattern and so I believe this should be centralised.

Proposed implementation:
```scss
.p-inline-images .p-inline-images__logo.is-wide {
  max-width: 9rem;
  max-height: none;
}
```
