### ISSUE TITLE
“is-inline” button margin becomes 0 at <875px screen width

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#3387]
Vanilla’s style sheet includes this:
```css
@(min-width: 875px)
[class*="p-button"].is-inline {
    margin-left: 1rem;
    width: auto;
}
```

So when the viewport width is ≥875px, an inline button has a nice left margin:

> ![image](https://user-images.githubusercontent.com/19801137/98239449-e3416500-1f5f-11eb-9bac-2892b0f875de.png)

But at a viewport width of <875px, the button is smooshed against the preceding text:

> ![image](https://user-images.githubusercontent.com/19801137/98239584-14ba3080-1f60-11eb-857b-6238082d404e.png)

I can’t think of any reason for this margin to be viewport-dependent.

(Discovered while investigating [ubuntu.com#8633](https://github.com/canonical-web-and-design/ubuntu.com/issues/8633).)
