### ISSUE TITLE
Stepped list targeting headings

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3757]
## Pattern to amend
The stepped-list pattern is using `h3` to target elements. For example:
```scss
h3.p-stepped-list__title::before {
    width: 2.5rem;
}
```

## Visual
Used in https://juju.is/tutorials but using a `p` instead of `h3`:
![image](https://user-images.githubusercontent.com/1413534/119333676-0c1e1300-bc82-11eb-831c-949668b02401.png)

## Context
This is commonly down across tutorials.
