### ISSUE TITLE
Mobile modal should not take whole screen

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#3906]
We decided to not make the modal take whole height of the screen on mobile.

# Initial proposal:

## Pattern to amend

Modal

## Visual

<img width="384" alt="Screen Shot 2021-08-04 at 3 32 34 pm" src="https://user-images.githubusercontent.com/361637/128127344-5318169e-67d9-4c35-b3e5-86565846ac3a.png">

## Context

The above visual was designed for ubuntu.com so that when viewing the modal on mobile the actions fit nicely at the bottom of the screen rather than having extra space at the bottom of the modal below the buttons, like this:

<img width="352" alt="Screen Shot 2021-08-04 at 3 34 43 pm" src="https://user-images.githubusercontent.com/361637/128127664-832d91c7-e5ae-47f2-8b2e-405257887f26.png">

I implemented this as a local override with:

```scss
.p-modal--sticky-footer .p-modal__dialog {
    display: grid;
    grid-template-rows: auto 1fr auto;
}
```

This could be a variant, or maybe this is how it should always appear on small screens.
