### ISSUE TITLE
Provide Canonical style title capitalise utility

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#3955]
Sometimes it is necessary to display dynamic data using the Canonical style title case (uppercase first letter of the first word). Using `text-transform: capitalize` capitalises the first letter of each word.

## Context

When dynamic data needs to be displayed in a title.

## Example

I've implemented this in the following way, but it would be nice as a utility in Vanilla.

```css
.u-text--capitalise-first::first-letter {
  text-transform: capitalize;
}
```
