### ISSUE TITLE
Provide dense version of inline notification

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#3970]
## Pattern to amend

Notification

## Visual

<img width="411" alt="Screen Shot 2021-09-06 at 2 45 22 pm" src="https://user-images.githubusercontent.com/361637/132162133-e363cad2-d36b-4b4e-8724-269a6d384092.png">

## Context

While trying to implement the visual above I first tried the following:

```html
<div class="p-notification--caution is-borderless is-inline">
  <div class="p-notification__content">
    <p class="p-notification__message">Subscription expired</p>
  </div>
</div>
```
This had too much spacing above, below and between the icon and the text.

<img width="414" alt="Screen Shot 2021-09-06 at 2 46 03 pm" src="https://user-images.githubusercontent.com/361637/132162336-73a5c8c2-b7b3-42b9-93df-723f2159b9c9.png">

After adding `u-no-margin--bottom` that corrected the bottom spacing, but there wasn't away to correct the rest of the spacing.

<img width="418" alt="Screen Shot 2021-09-06 at 2 46 20 pm" src="https://user-images.githubusercontent.com/361637/132162348-84978992-421e-4eaa-af4d-1adfee3e5984.png">

**Comment by huwshimi** [comment]
Using the following appears to provide the correct spacing:

```scss
  .is-dense {
    background-position-y: center;
    margin-bottom: 0;
    padding-left: $sph-inner--large;

    .p-notification__content {
      padding-top: 0;
    }
  }
```
